"""Static gallery generation for GitHub Pages.

``flyer gallery`` renders every flyer found under ``output/`` into a single
self-contained page with its campaign, headline, QA score and approval state.
The GitHub Actions Pages workflow publishes it so you can review a week of
flyers from a phone.
"""

from __future__ import annotations

import html
import json
import shutil
from pathlib import Path

from .config import get_settings
from .logging_setup import get_logger
from .pipeline import history

log = get_logger(__name__)

PAGE = """<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{
    color-scheme: light dark;
    --bg: #f6f7f9; --card: #ffffff; --ink: #16191d; --muted: #626b78;
    --line: #e2e6ec; --ok: #17794a; --bad: #b3261e; --accent: #1e4fd8;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --bg:#0f1216; --card:#171b21; --ink:#e8ecf1; --muted:#9aa4b2;
             --line:#262c35; --ok:#4ade80; --bad:#f87171; --accent:#7aa2ff; }}
  }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; background:var(--bg); color:var(--ink);
         font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif; }}
  header {{ padding:32px 24px 8px; max-width:1200px; margin:0 auto; }}
  h1 {{ font-size:26px; margin:0 0 6px; letter-spacing:-0.02em; }}
  .sub {{ color:var(--muted); font-size:14px; }}
  .stats {{ display:flex; gap:20px; flex-wrap:wrap; margin:18px 0 0; padding:0; list-style:none; }}
  .stats li {{ background:var(--card); border:1px solid var(--line); border-radius:10px;
               padding:10px 16px; }}
  .stats b {{ display:block; font-size:22px; }}
  main {{ max-width:1200px; margin:0 auto; padding:24px;
          display:grid; gap:20px; grid-template-columns:repeat(auto-fill,minmax(260px,1fr)); }}
  .card {{ background:var(--card); border:1px solid var(--line); border-radius:14px;
           overflow:hidden; display:flex; flex-direction:column; }}
  .card img {{ width:100%; display:block; background:var(--line); aspect-ratio:4/5;
               object-fit:cover; }}
  .meta {{ padding:14px 16px 16px; display:flex; flex-direction:column; gap:6px; }}
  .headline {{ font-weight:650; letter-spacing:-0.01em; }}
  .row {{ display:flex; gap:8px; flex-wrap:wrap; align-items:center;
          color:var(--muted); font-size:12.5px; }}
  .tag {{ border:1px solid var(--line); border-radius:999px; padding:2px 9px; }}
  .ok {{ color:var(--ok); }} .bad {{ color:var(--bad); }}
  footer {{ max-width:1200px; margin:0 auto; padding:8px 24px 48px; color:var(--muted);
            font-size:13px; }}
  a {{ color:var(--accent); }}
  .empty {{ grid-column:1/-1; text-align:center; padding:80px 20px; color:var(--muted); }}
</style>
<header>
  <h1>{title}</h1>
  <div class="sub">{subtitle}</div>
  <ul class="stats">
    <li><b>{total}</b>flyers</li>
    <li><b>{passed}</b>passed QA</li>
    <li><b>{approved}</b>approved</li>
    <li><b>{clients}</b>clients</li>
  </ul>
</header>
<main>
{cards}
</main>
<footer>Generated by <a href="https://github.com/engineeringwithjp/flyer-generator">flyer-generator</a>. Newest first.</footer>
"""

CARD = """  <article class="card">
    <img src="{src}" alt="{alt}" loading="lazy">
    <div class="meta">
      <div class="headline">{headline}</div>
      <div class="row"><span class="tag">{campaign}</span><span class="tag">{layout}</span></div>
      <div class="row"><span>{date}</span><span>{client}</span>
        <span class="{qa_class}">QA {qa}</span><span>{approved}</span></div>
    </div>
  </article>"""


def _collect() -> list[dict]:
    """Every rendered flyer on disk, newest first, joined to its history entry."""
    settings = get_settings()
    output = settings.paths.output
    if not output.exists():
        return []

    entries = {e.get("flyer_id"): e for e in history.load_history()}
    items: list[dict] = []

    for meta_path in sorted(output.rglob("flyer-*.json"), reverse=True):
        try:
            data = json.loads(meta_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        spec = data.get("spec", {})
        image_path = Path(data.get("image_path", ""))
        if not image_path.exists():
            continue
        flyer_id = spec.get("id", "")
        entry = entries.get(flyer_id, {})
        items.append(
            {
                "flyer_id": flyer_id,
                "image": image_path,
                "thumb": image_path.parent / "thumbs" / f"{image_path.stem}.jpg",
                "headline": spec.get("text", {}).get("headline", "(no headline)"),
                "campaign": spec.get("campaign_id", ""),
                "layout": spec.get("layout", {}).get("name", ""),
                "client": spec.get("client_id", ""),
                "date": meta_path.parent.parent.name,
                "qa": data.get("qa_score", 0),
                "qa_passed": bool(data.get("qa_passed")),
                "approved": entry.get("approved"),
            }
        )
    return items


def build_gallery(out_dir: Path, title: str = "Flyer Gallery") -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    images_dir = out_dir / "flyers"
    images_dir.mkdir(exist_ok=True)

    items = _collect()
    cards: list[str] = []
    clients: set[str] = set()
    passed = approved = 0

    for item in items:
        source = item["thumb"] if item["thumb"].exists() else item["image"]
        dest_name = f"{item['flyer_id'] or source.stem}{source.suffix}"
        shutil.copy2(source, images_dir / dest_name)

        clients.add(item["client"])
        passed += 1 if item["qa_passed"] else 0
        approved += 1 if item["approved"] else 0

        approval = (
            "approved"
            if item["approved"] is True
            else "rejected"
            if item["approved"] is False
            else "awaiting review"
        )
        cards.append(
            CARD.format(
                src=f"flyers/{html.escape(dest_name)}",
                alt=html.escape(item["headline"]),
                headline=html.escape(item["headline"]),
                campaign=html.escape(item["campaign"]),
                layout=html.escape(item["layout"]),
                date=html.escape(item["date"]),
                client=html.escape(item["client"]),
                qa=item["qa"],
                qa_class="ok" if item["qa_passed"] else "bad",
                approved=approval,
            )
        )

    if not cards:
        cards = ['  <div class="empty">No flyers yet. Run <code>flyer generate</code>.</div>']

    page = PAGE.format(
        title=html.escape(title),
        subtitle=f"{len(items)} flyer(s) across {len(clients) or 0} client(s)",
        total=len(items),
        passed=passed,
        approved=approved,
        clients=len(clients),
        cards="\n".join(cards),
    )
    index = out_dir / "index.html"
    index.write_text(page, encoding="utf-8")
    (out_dir / ".nojekyll").write_text("", encoding="utf-8")
    log.info("Gallery built at %s (%d flyers)", index, len(items))
    return index
