"""Disk hygiene.

Three things make this project grow without bound if left alone:

* rendered flyers accumulate in ``output/`` forever
* candidate frames from a media scan are kept at full capture resolution
* approved photography is stored far larger than any flyer can use

None of that is necessary. A 1080x1350 flyer never needs more than about
2400px on the long edge even after a focal crop, and once a flyer is in Google
Drive the local copy is a cache, not an archive.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from datetime import date, timedelta
from pathlib import Path

from PIL import Image

from .config import Settings, get_settings
from .logging_setup import get_logger

log = get_logger(__name__)

IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp"}


def directory_size(path: Path) -> int:
    """Bytes on disk under ``path``. Missing directories are zero, not an error."""
    if not path.exists():
        return 0
    return sum(f.stat().st_size for f in path.rglob("*") if f.is_file())


def human(size: int) -> str:
    value = float(size)
    for unit in ("B", "KB", "MB", "GB"):
        if value < 1024 or unit == "GB":
            return f"{value:.0f} {unit}" if unit in ("B", "KB") else f"{value:.1f} {unit}"
        value /= 1024
    return f"{value:.1f} GB"


@dataclass
class StorageReport:
    freed_bytes: int = 0
    output_runs_removed: int = 0
    frames_removed: int = 0
    assets_downscaled: int = 0
    details: list[str] = field(default_factory=list)

    def summary(self) -> str:
        parts = []
        if self.output_runs_removed:
            parts.append(f"{self.output_runs_removed} old run(s)")
        if self.frames_removed:
            parts.append(f"{self.frames_removed} unreviewed frame(s)")
        if self.assets_downscaled:
            parts.append(f"{self.assets_downscaled} asset(s) downscaled")
        what = ", ".join(parts) or "nothing to do"
        return f"{what} — {human(self.freed_bytes)} freed"


# ------------------------------------------------------------------- output


def prune_output(
    keep_days: int = 7,
    dry_run: bool = False,
    settings: Settings | None = None,
) -> StorageReport:
    """Delete rendered flyers older than ``keep_days``.

    Only date-named run folders are touched, and a run is only removed when its
    flyers reached Google Drive: the metadata sidecar records the Drive file id,
    so an un-uploaded run is never deleted regardless of age.
    """
    import json

    settings = settings or get_settings()
    report = StorageReport()
    output = settings.paths.output
    if not output.exists():
        return report

    cutoff = date.today() - timedelta(days=keep_days)

    for run_dir in sorted(output.iterdir()):
        if not run_dir.is_dir() or run_dir.name.startswith((".", "_")):
            continue
        try:
            when = date.fromisoformat(run_dir.name)
        except ValueError:
            continue  # not a date folder; leave it alone
        if when >= cutoff:
            continue

        uploaded, total = 0, 0
        for meta in run_dir.rglob("flyer-*.json"):
            total += 1
            try:
                if json.loads(meta.read_text(encoding="utf-8")).get("drive_file_id"):
                    uploaded += 1
            except (OSError, json.JSONDecodeError):
                pass

        if total and uploaded < total:
            report.details.append(f"kept {run_dir.name}: {total - uploaded} flyer(s) not in Drive")
            continue

        size = directory_size(run_dir)
        if not dry_run:
            shutil.rmtree(run_dir, ignore_errors=True)
        report.freed_bytes += size
        report.output_runs_removed += 1
        report.details.append(f"removed {run_dir.name} ({human(size)})")

    return report


# -------------------------------------------------------------- raw candidates


def prune_unreviewed_frames(
    keep_top: int = 40,
    dry_run: bool = False,
    settings: Settings | None = None,
) -> StorageReport:
    """Drop the weakest unreviewed candidate frames.

    A media scan produces far more candidates than anyone will review. Approved
    assets and the highest-scoring candidates are kept; the tail is deleted,
    and can always be regenerated by re-running the scan.
    """
    from .assets.catalog import AssetCatalog

    settings = settings or get_settings()
    report = StorageReport()
    catalog = AssetCatalog.load()

    candidates = [
        a
        for a in catalog.index.assets
        if not a.production_eligible and not a.is_synthetic and "/raw/" in a.path.replace("\\", "/")
    ]
    candidates.sort(key=lambda a: a.quality_score, reverse=True)

    for asset in candidates[keep_top:]:
        path = settings.paths.root / asset.path
        if not path.exists():
            continue
        size = path.stat().st_size
        if not dry_run:
            path.unlink(missing_ok=True)
            path.with_suffix(".json").unlink(missing_ok=True)
        report.freed_bytes += size
        report.frames_removed += 1

    if report.frames_removed:
        report.details.append(
            f"kept the top {keep_top} candidates, removed {report.frames_removed}"
        )
    return report


# ------------------------------------------------------------------- assets


def downscale_image(path: Path, max_edge: int, quality: int = 88) -> int:
    """Shrink an image in place. Returns bytes saved (0 if already small)."""
    try:
        with Image.open(path) as handle:
            image = handle.convert("RGB")
            width, height = image.size
    except Exception as exc:
        log.warning("Could not open %s: %s", path.name, exc)
        return 0

    if max(width, height) <= max_edge:
        return 0

    before = path.stat().st_size
    ratio = max_edge / max(width, height)
    resized = image.resize(
        (max(int(width * ratio), 1), max(int(height * ratio), 1)), Image.Resampling.LANCZOS
    )
    target = path.with_suffix(".jpg")
    resized.save(target, format="JPEG", quality=quality, optimize=True, progressive=True)
    if target != path:
        path.unlink(missing_ok=True)
    return max(before - target.stat().st_size, 0)


def downscale_library(
    max_edge: int | None = None,
    dry_run: bool = False,
    settings: Settings | None = None,
) -> StorageReport:
    """Bring every stored photo down to the largest size a flyer can use."""
    settings = settings or get_settings()
    max_edge = max_edge or settings.asset_max_edge
    report = StorageReport()

    roots = [settings.paths.clients, settings.paths.assets]
    for root in roots:
        if not root.exists():
            continue
        for path in sorted(root.rglob("*")):
            if path.suffix.lower() not in IMAGE_SUFFIXES or not path.is_file():
                continue
            if "logo" in path.parts or "fonts" in path.parts:
                continue  # logos are line art; fonts are not images
            if dry_run:
                try:
                    with Image.open(path) as image:
                        if max(image.size) > max_edge:
                            report.assets_downscaled += 1
                            report.freed_bytes += int(path.stat().st_size * 0.85)
                except Exception:
                    pass
                continue
            saved = downscale_image(path, max_edge)
            if saved:
                report.assets_downscaled += 1
                report.freed_bytes += saved

    if report.assets_downscaled:
        report.details.append(f"downscaled to {max_edge}px on the long edge")
    return report


# ------------------------------------------------------------------ overview


def usage(settings: Settings | None = None) -> dict[str, int]:
    """Bytes per area, for `flyer storage`."""
    settings = settings or get_settings()
    root = settings.paths.root
    clients = root / "clients"
    raw = sum(directory_size(p / "assets" / "raw") for p in clients.glob("*") if p.is_dir())
    approved = sum(
        directory_size(p / "assets" / "approved") for p in clients.glob("*") if p.is_dir()
    )
    areas = {
        "output (rendered flyers)": directory_size(settings.paths.output),
        "approved photography": approved,
        "unreviewed candidates": raw,
        "shared asset library": directory_size(settings.paths.assets),
        "git history": directory_size(root / ".git"),
        "python environment": directory_size(root / ".venv"),
        "claude worktrees": directory_size(root / ".claude" / "worktrees"),
    }
    return areas


def stale_worktrees(settings: Settings | None = None) -> list[tuple[Path, int]]:
    """Claude Code worktrees are scratch checkouts and duplicate the whole repo."""
    settings = settings or get_settings()
    base = settings.paths.root / ".claude" / "worktrees"
    if not base.exists():
        return []
    return [(p, directory_size(p)) for p in base.iterdir() if p.is_dir()]
